# Generated by Django 2.2.4 on 2020-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0003_auto_20200423_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='state',
            field=models.IntegerField(choices=[(0, 'Created'), (10, 'Study'), (20, 'Reported'), (30, 'Monitoring'), (40, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
