# Generated by Django 2.2.4 on 2020-04-24 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0004_auto_20200423_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='cve_cvss',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='affected_versions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='impact',
            field=models.IntegerField(choices=[(0, 'Informational'), (10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')], default=0),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='solution',
            field=models.TextField(null=True),
        ),
    ]
