# Generated by Django 2.2.4 on 2020-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0005_auto_20200424_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'verbose_name_plural': 'Vulnerabilities'},
        ),
        migrations.RenameField(
            model_name='cve',
            old_name='cve_cvss',
            new_name='cve_cvss_score',
        ),
        migrations.AddField(
            model_name='cve',
            name='cve_cvss_vector',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
