# Generated by Django 2.2.4 on 2020-04-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0006_auto_20200424_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerability',
            old_name='affected_versions',
            new_name='notes',
        ),
    ]
