# Generated by Django 2.2.4 on 2020-04-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0008_vulnerability_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='exploited_in_the_wild',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cve_cvss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cve_cvss_vector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
